apiVersion: v1
kind: Secret
metadata:
  name: repo-prometheus
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: prometheus-community-helm-chart
  url: https://prometheus-community.github.io/helm-charts
  project: '*'
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-grafana
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: grafana-helm-chart
  url: https://grafana.github.io/helm-charts
  project: '*'
  type: helm
