apiVersion: v1
kind: Secret
metadata:
  name: repo-prometheus
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://prometheus-community.github.io/helm-charts
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-grafana
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://grafana.github.io/helm-charts
  type: helm
