---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: base-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: base apps for all environments
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
