---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: demo apps for testing
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
