apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jpradoar/gitops.git
        revision: main
        directories:
          - path: apps/dev/*
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: default
      source:
        repoURL: https://github.com/jpradoar/helm-chart.git
        targetRevision: main
        chart: '{{path.basename}}'     # el nombre del chart se toma del folder basename (ej: domoticz → domoticz)
        helm:
          valueFiles:
            - '{{path}}'               # ruta relativa al repo gitops → apps/dev/values-<app>.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
