- name: prometheus-community #kube-prometheus-stack
  version: "41.7.3"
  namespace: monitoring
  repoURL: https://prometheus-community.github.io/helm-charts

#- name: kube-state-metrics
#  version: "5.11.1" 
#  namespace: monitoring
#  repository: oci://ghcr.io/prometheus-community/charts/kube-state-metrics

- name: loki-stack
  version: "v2.9.3"
  namespace: monitoring
  repoURL: https://grafana.github.io/helm-charts

- name: grafana
  version: "7.3.6"
  namespace: monitoring
  repoURL: https://grafana.github.io/helm-charts
