- name: domoticz
  version: "1.0.0"
  namespace: domoticz

- name: external-secrets
  applicationName: external-secrets
  repository: https://charts.external-secrets.io
  version: 0.15.1
  namespace: external-secrets
