- applicationName: domoticz
  name: domoticz
  version: 1.0.0
  namespace: domoticz-demo

- applicationName: prometheus
  name: prometheus
  version: 45.0.0
  namespace: monitoring

- applicationName: grafana
  name: grafana
  version: 8.20.0
  namespace: monitoring

- applicationName: loki
  name: loki
  version: 2.10.0
  namespace: monitoring
