- applicationName: domoticz
  name: domoticz
  version: 1.0.0
  namespace: domoticz-demo
  chartRepoURL: https://jpradoar.github.io/helm-chart

- applicationName: prometheus
  name: prometheus
  version: 45.0.0
  namespace: monitoring
  chartRepoURL: https://prometheus-community.github.io/helm-charts

- applicationName: grafana
  name: grafana
  version: 8.20.0
  namespace: monitoring
  chartRepoURL: https://grafana.github.io/helm-charts

- applicationName: loki
  name: loki
  version: 2.10.0
  namespace: monitoring
  chartRepoURL: https://grafana.github.io/helm-charts
