{
 "title": "Logs por namespace",
 "tags": [
  "loki",
  "observability",
  "usage"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({namespace!=\"\"}, namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values({namespace=~\"$namespace\", app!=\"\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volumen total (GB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({namespace=~\"$namespace\",app=~\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Ingesta actual (MB/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megabytes/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({namespace=~\"$namespace\",app=~\"$app\"}[1m])) / 60 / 1e6"
    }
   ]
  },
  {
   "title": "Líneas/s (prom 1 m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({namespace=~\"$namespace\",app=~\"$app\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cantidad de líneas de log",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {namespace=~\"$namespace\", app=~\"$app\"}[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Tendencia de líneas de log por App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (app) (\n  count_over_time({namespace=~\"$namespace\", app=~\"$app\"}[10m])\n)\n"
    }
   ]
  },
  {
   "title": "Tendencia de Volumen por Namespace (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace)(bytes_over_time({namespace=~\"$namespace\",app=~\"$app\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Tendencia de Logs/s por Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(namespace)(rate({namespace=~\"$namespace\",app=~\"$app\"}[1m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top 10 Apps por líneas de log generadas",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by(app)(\n    count_over_time({namespace=~\"$namespace\", app=~\"$app\"}[$__range])\n  )\n)"
    }
   ]
  },
  {
   "title": "Top 10 Pods por líneas de log generadas",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by(pod)(\n    count_over_time({app=~\"$app\"}[$__range])\n  )\n)"
    }
   ]
  },
  {
   "title": "Top 10 Namespaces por Volumen (GB)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (namespace) (\n    bytes_over_time({namespace=~\"$namespace\", app=~\"$app\"}[$__range])\n  ))"
    }
   ]
  },
  {
   "title": "Top 10 Apps por Volumen (GB)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (namespace, app) (\n    bytes_over_time(\n      {namespace=~\"$namespace\", app=~\"$app\"}[$__range]\n    )\n  )\n)"
    }
   ]
  }
 ]
}