{
 "title": "Kubernetes Events",
 "description": "Kubernetes Events",
 "tags": [
  "events",
  "kubernetes",
  "devops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes events",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"default\", app=\"mqtt-event-exporter\"} |= ``"
    }
   ]
  },
  {
   "title": "EVENT TYPE (in 6h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Normal\" [6h]))",
     "legendFormat": "Normal"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Warning\" [6h]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "EVENT REASON (in 6h)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Started\" [6h]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Created\" [6h]))",
     "legendFormat": "Created"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Pulled\" [6h]))",
     "legendFormat": "Pulled"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Pulling\" [6h]))",
     "legendFormat": "Pulling"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Scheduled\" [6h]))",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"SuccessfulCreate\" [6h]))",
     "legendFormat": "SuccessfulCreate"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"ScalingReplicaSet\" [6h]))",
     "legendFormat": "ScalingReplicaSet"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Killing\" [6h]))",
     "legendFormat": "Killing"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Unhealthy\" [6h]))",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(count_over_time({namespace=~\"default\", app=\"mqtt-event-exporter\"} |= \"Killing\" [6h]))",
     "legendFormat": "Killing"
    }
   ]
  }
 ]
}